ls:
    image: 
        name : rclone/rclone
        entrypoint: [""]
    script:
        - export AWS_ACCESS_KEY_ID=$S3_USERNAME
        - export AWS_SECRET_ACCESS_KEY=$S3_PASSWORD
        - rclone config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr
        - "rclone ls monS3:funcampr"
        - "mkdir funcampr-gateway"
        - "mkdir funcampr-allinone"
        - "rclone copy monS3:funcampr/ressources.zip funcampr-gateway"
        - "unzip funcampr-gateway/ressources.zip -d funcampr-allinone"
        - "wget -P funcampr-gateway https://git.lab.sspcloud.fr/funcamp-r/funcamp-r-windows-grimoire-launcher/-/archive/master/funcamp-r-windows-grimoire-launcher-master.zip"
        - "unzip funcampr-gateway/funcamp-r-windows-grimoire-launcher-master.zip -d funcampr-gateway"
        - "rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/Grimoire funcampr-allinone/ressources"
        - "tar cvf funcampr-gateway/funcampr.tar funcampr-allinone/ressources"
        - "rclone copy funcampr-gateway/funcampr.tar monS3:funcampr"