fusion:
    image: 
        name : rclone/rclone
        entrypoint: [""]
    script:
        - export AWS_ACCESS_KEY_ID=$S3_USERNAME
        - export AWS_SECRET_ACCESS_KEY=$S3_PASSWORD
        - rclone config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr
        - "rclone ls monS3:funcampr"
        - "mkdir funcampr-gateway"
        - "mkdir funcampr-allinone"
        - "rclone copy monS3:funcampr/ressources.zip funcampr-gateway"
        - "unzip -q funcampr-gateway/ressources.zip -d funcampr-allinone"
        - "wget -P funcampr-gateway https://git.lab.sspcloud.fr/funcamp-r/funcamp-r-windows-grimoire-launcher/-/archive/master/funcamp-r-windows-grimoire-launcher-master.zip"
        - "unzip -q funcampr-gateway/funcamp-r-windows-grimoire-launcher-master.zip -d funcampr-gateway"
        - "mkdir funcampr-allinone/ressources/Grimoire"
        - "rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/Grimoire funcampr-allinone/ressources/Grimoire"
        - "rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/START_grimoire.hta funcampr-allinone"
        - "wget -P funcampr-gateway https://git.lab.sspcloud.fr/funcamp-r/funcamp-r-windows-solarus/-/jobs/artifacts/master/download?job=game-package"
        - "unzip -q funcampr-gateway/icaRius-windows.zip -d funcampr-gateway"
        - "rclone copy funcampr-gateway/icaRius-windows funcampr-allinone/ressources"
        - "tar czvf funcampr-gateway/funcampr.tar.gz funcampr-allinone"
        - "rclone copy funcampr-gateway/funcampr.tar.gz monS3:funcampr"