ls:
    image: 
        name : rclone/rclone
        entrypoint: [""]
    script:
        - export AWS_ACCESS_KEY_ID=$S3_USERNAME
        - export AWS_SECRET_ACCESS_KEY=$S3_PASSWORD
        - rclone config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr
        - "rclone ls monS3:funcampr"
