name: packaging all-in-one funcampR dock

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  sync-job:
    runs-on: ubuntu-latest
    # container: rclone/rclone
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        AWS_S3_ENDPOINT: https://minio.lab.sspcloud.fr
  rclone-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: |
          'config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr'
          'ls monS3:funcampr'
