name: packaging all-in-one funcampR dock

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # container: rclone/rclone
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        AWS_S3_ENDPOINT: https://minio.lab.sspcloud.fr
